# Generated by Django 5.2 on 2025-05-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_remove_employee_firstname_remove_employee_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
