# Generated by Django 5.2 on 2025-05-13 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('staff', '0001_initial'),
        ('travel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
        migrations.AddField(
            model_name='travelguide',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employee'),
        ),
        migrations.AddField(
            model_name='travelimage',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.travels'),
        ),
        migrations.AddField(
            model_name='travelguide',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.travels'),
        ),
        migrations.AddField(
            model_name='travelcategory',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.travels'),
        ),
        migrations.AddField(
            model_name='review',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.travels'),
        ),
    ]
