# Generated by Django 5.2 on 2025-05-13 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('travel', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travels',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travels',
            name='guests_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='travels',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.region'),
        ),
    ]
